/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    KsgButton: typeof import('@ksg/ksg-components')['KsgButton']
    KsgFab: typeof import('@ksg/ksg-components')['KsgFab']
    KsgFabItem: typeof import('@ksg/ksg-components')['KsgFabItem']
    KsgFormText: typeof import('./../src/components/KsgFormText.vue')['default']
    KsgHeader: typeof import('./../src/components/ksgLayout/ksgHeader.vue')['default']
    KsgKim: typeof import('./../src/components/KsgKim.vue')['default']
    KsgLayout: typeof import('@ksg/ksg-components')['KsgLayout']
    KsgPageContainer: typeof import('@ksg/ksg-components')['KsgPageContainer']
    KsgPageWrapper: typeof import('./../src/components/KsgPageWrapper.vue')['default']
    KsgSvgIcon: typeof import('./../src/components/KsgSvgIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
